### ISSUE TITLE
Ignore `tags` in YAML frontmatter

### ISSUE THREAD

**Issue by ChristinWhite** [imdone/imdone#100]
**Is your feature request related to a problem? Please describe.**
I use Imdone inside of my Obsidian vault and I'd like to have the tags in the YAML frontmatter only be used by Obsidian, not the card itself since they are two different contexts for looking at the same information and don't always make sense to be mirrored.

For example, in Obsidian I may have this:

```yaml
---
tags: [ Classes/Kanban/Card, Roles/Creator/Developer ]
---
```

In Imdone however I don't need quite that set of contextual information, Imdone already knows it's a card and while including `roles` makes sense I may want to omit the hierarchy and just use `+Developer`. 

Right now this looks quite messy in Imdone.

<img src="https://user-images.githubusercontent.com/1746405/116451629-bbee9500-a82a-11eb-8bab-9d53de12a8e6.png" width="50%" height="50%">

**Describe the solution you'd like**
Good question, there are a number of ways to do this and they may all have drawbacks. A couple of ideas:

1. Have a global `ignore frontmatter tags` setting, this is pretty inflexible though and at times it may still be useful to define tags in the YAML frontmatter.
2. Only include tags with prefix `x`, `+<tagname>` for example. Also not very flexible. This would be more useful if #92 was implemented.
3. Explicitly exclude an array of tags at the project level, this could take a lot of manual work though if someone uses a lot of Obsidian tags.
4. Card level `ignore frontmatter tags` setting, this is more flexible but potentially a bit verbose.
5. I think my ideal way would be to designate an alternate `imdone tags` key at the project level so I could do this:

```yaml
---
tags: [ Classes/Kanban/Card, Roles/Creator/Developer ]
imdone tags: [ Improvement, Developer, <component name> ]
--- 
```

You could potentially set a default behavior too, 'if `imdone tags` key doesn't exist include or exclude `tags`'.

There are probably other and potentially better ways as well that I didn't think of.

**Describe alternatives you've considered**
I'm not sure there are good alternatives besides:

1. Try to ignore the extra tags in Imdone
2. Just don't use YAML tags for cards specifically in Obsidian, breaking the conventions I've defined for my Obsidian notes in this specific context.

**Comment by piascikj** [comment]
Can you use the **Ignore file front-matter tags" board setting for this?
