### ISSUE TITLE
delete button should be difficult to hit unintentionally

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#101]
**Is your feature request related to a problem? Please describe.**
+ the `delete` button is too easy to hit. A single `tab` from the filter box followed by `enter` could lead to a lot of data being deleted.
+ the location of the button in the UI is misleading. The first ui element after the filter box is the `copy filter url` button, but a tab doesn't take one there.

I think I unintentionally ended up deleting 100+ tasks across my markdown file this morning. Luckily I had backed up last night (a week old habit!), and I didn't make many edits this morning, so I was able to recover everything.

**Describe the solution you'd like**
+ put the delete button last amongst the buttons at the top. 
    + I would prefer putting it in a menu to make it less accessible since I imagine it is not used often. 

**Describe alternatives you've considered**
-- not applicable --

**Additional context**
-- not applicable --

**Comment by piascikj** [comment]
This has been implemented. `shift+delete` deletes without prompt. Delete by itself asks for confirmation.
