### ISSUE TITLE
Card editor fails to be displayed for projects using single file option

### ISSUE THREAD

**Issue by FLY1NN** [imdone/imdone#106]
**Describe the bug**
Card editor fails to be displayed when a project is created with "Use a single file for all new cards". An error is logged to the developer console reading "TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined".

**To Reproduce**
1. Create a new project using "Use a single file for all new cards".
2. Click create "Add a card" or press <space>.

**Expected behavior**
The card editor should be displayed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: N/A
 - Imdone Version: 1.17.3

**DoD**
- [ ] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by piascikj** [comment]
Can you provide the relevant portion of your log file?

**Comment by FLY1NN** [comment]
If you mean the log located at AppData/Roaming/imdone/log.log, there are no relevant entries (no messages are logged when add is clicked). The only output I can find is that printed to the dev console, the full entry is:

```log
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120)
    at Object.join (path.js:375)
    at wa.appendNewCardsTo (app.183629b7.js:1)
    at wa.getNewCardsFile (app.183629b7.js:1)
    at wa.getNewCardFileFrontMatter (app.183629b7.js:1)
    at wa.getNewCardTemplate (app.183629b7.js:1)
    at wa.newCard (app.183629b7.js:1)
    at o.addCard (app.183629b7.js:1)
    at click (app.183629b7.js:1)
    at rt (chunk-vendors.b6384613.js:75)
```

If you are referencing a different log file than the one mentioned above, specify the path and I'd be happy to provide-
