### ISSUE TITLE
Relationship between imdone & imdone-core

### ISSUE THREAD

**Issue by telenieko** [imdone/imdone#109]
There are two "main" repositories on the imdone org: `imdone` & `imdone-core`.

The first one is used mostly as an issue tracker for `imdone`, which is a common practice on closed-source projects. But then there is `imdone-core` which is MIT Licensed and has source code.

Which begs the question: What is the relationship between both repositories? Or more specifically: what is in imdone that is not in the imdone-core repository?

Which of the following would be "correct"?:
1. imdone is a binary release of imdone-core,
2. imdone is -core on steroids. imdone is Propietary license, imdone-core is MIT

Question arose when I was packaging imdone for https://scoop.sh/ and had to fill the License property.

**Comment by telenieko** [comment]
Please clarify licensing so [lukesampson/scoop-extras#6156] can move forward.

**Comment by piascikj** [comment]
Sorry for the late reply.  Number 2 is correct.   Imdone is imdone-core on
steroids.

**Comment by telenieko** [comment]
Thanks!
