### ISSUE TITLE
Filebased Metadata

### ISSUE THREAD

**Issue by rismay** [imdone/imdone#11]
**Is your feature request related to a problem? Please describe.**
Adding metadata to cards is amazing. However, I find that I have to do add it over and over again

**Describe the solution you'd like**
It would be great to add metadata to a file that applies to all cards that day. 

**Additional context**
For example, it would be nice to be able to add a context to a file, rather than to each individual card in that file.

**Comment by piascikj** [comment]
@rismay This is available in the current version.  Take a look at [Front matter](https://imdone.io/docs/#/settings?id=front-matter)

**Comment by piascikj** [comment]
@rismay Did the documentation help?
