### ISSUE TITLE
Imdone ignores `.imdoneignore`

### ISSUE THREAD

**Issue by bluebirch** [imdone/imdone#120]
**Describe the bug**
I use the same Imdone project on two laptops, one Linux and one Windows, synced with [Syncthing](https://syncthing.net). The `.imdoneignore` file works as expected on the Linux side, but not on Windows.

**To Reproduce**
I have the same `.imdoneignore` file on both laptops, with the following content:

```
.obsidian
.trash
.stversions
```

**Expected behavior**
I would expect all files from the `.stversions` subdirectory to be silently ignored. It works as expected on the Linux side, but not on Windows. Imdone finds files in the `.stversions` subdirectory.

**Desktop (please complete the following information):**
 - OS: Windows 10 & Ubuntu Linux 20.04 LTS.
 - Imdone Version 1.23

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
@bluebirch Is this working for you now?

**Comment by bluebirch** [comment]
Unfortunately no. Imdone still finds files in `.stversions` folder.

**Comment by piascikj** [comment]
I'll have a new release for you to test today.  It has a change to the line ending for ignores on windows.  I haven't had enough time to retest yet, but I'm hoping it will solve the issue.

**Comment by bluebirch** [comment]
> I'll have a new release for you to test today. It has a change to the line ending for ignores on windows. I haven't had enough time to retest yet, but I'm hoping it will solve the issue.

Sounds great. Can't figure out how to find that release though...

**Comment by bluebirch** [comment]
Still the same. Sitting with Linux and Windows laptop in front of me as I write this, same working directory, in sync with Syncthing -- and different kanban boards in Imdone (because of files found in `.stversions`).

**Comment by bluebirch** [comment]
I've managed to "solve" the problem (i.e. "make it go away"). What I did was (1) deleted the `.stversions` folder on the Windows laptop (thus letting Syncthing recreate it), (2) created a new temporary folder with a single markdown file with a kanban card, (3) excluded the new temporary folder in `.imdoneignore`. That worked as expected on both laptops. And now, when I have restored everything, it works. The `.stfolder` is excluded on both Windows and Linux.

Since I don't know exactly what made it work, I don't know what caused the problem. You mentioned windows/unix line endings. That one I had already tried. Maybe there was something with the directory itself. Attributes or permissions or something. I have no idea. The important thing is that it works, but a bit unsettling that I don't know why it didn't work.

**Comment by bluebirch** [comment]
I think I know what goes wrong. It seems like files with UTF-8 characters in the file name is not excluded. Maybe you need canocial normalizations of UTF-8 strings before comparisions?

**Comment by piascikj** [comment]
Looks like the ignore library I use has this, I just have to upgrade.  I'll get it in there for the next release.
[Fix paths with supported unicode chars not converted to posix by aquibm · Pull Request #46 · kaelzhang/node-ignore](https://github.com/kaelzhang/node-ignore/pull/46)

**Comment by piascikj** [comment]
@bluebirch Can you give me an example of a filename character that breaks it?

**Comment by bluebirch** [comment]
All files with `å`, `ä` or `ö` (common Swedish characters).

**Comment by piascikj** [comment]
@bluebirch Is this resolved with the latest release?  I tested with `å`, `ä` and `ö` in filenames with success.

**Comment by bluebirch** [comment]
It seems to work. 👍
