### ISSUE TITLE
Tabs are gone and add new project not working

### ISSUE THREAD

**Issue by Janvh** [imdone/imdone#124]
All tabs are gone and I can't add a new project. 

The button is not working at all

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/19709818/169488193-fd288657-7629-48be-821d-325cb1bbd5d4.png">

**Comment by piascikj** [comment]
Is this still an issue?

**Comment by Janvh** [comment]
No, it's not an issue anymore. Thanks
