### ISSUE TITLE
Wiki links with non-ASCII characters doesn't work

### ISSUE THREAD

**Issue by bluebirch** [imdone/imdone#127]
**Describe the bug**
As the title says.

**To Reproduce**
Wiki links like `[[Bjork]]` works as expected. Wiki links like `[[Björk]]` are not rendered as links at all.

**Expected behavior**
I expect `[[Björk]]` to be rendered as a link, just like `[[Bjork]]`.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Imdone Version 1.29.5

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
Fixed in imdone 1.41.0
