### ISSUE TITLE
Add a card doesn't respond anymore

### ISSUE THREAD

**Issue by Xapitoun** [imdone/imdone#128]
**Describe the bug**
Click on the "Add a card" icon doesn't working

**To Reproduce**

**Expected behavior**
When I click on this icon, nothing append. I cannot add any card…

**Screenshots**

**Desktop (please complete the following information):
 - OS: Linux 22.04 LTS
 - Imdone Version 1.31.2

**DoD**
- [ ] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by piascikj** [comment]
@Xapitoun Can you open devtools (view menu -> toggle developer tools) and see if there are any errors?
