### ISSUE TITLE
How to buy without GitHub?

### ISSUE THREAD

**Issue by ribtoks** [imdone/imdone#2]
I want to use the app only locally therefore I don't want to give access to my GitHub account in order to buy a license. Is there any way to buy a license with anything else like Stripe/PayPal?

**Comment by piascikj** [comment]
That's great!  Sorry for the inconvenience.  I don't have a way to do that right now, but can have imdone accept email/password sign in by the end of the weekend if that works for you.

**Comment by ribtoks** [comment]
@piascikj No problem. I tried trial version and decided that I'm not going to buy full version at this time. That's a very good start, I think it has great potential.

**Comment by piascikj** [comment]
Thatnks for the feedback.  What's missing that would make you want to buy a
license?
