### ISSUE TITLE
Generate work stats - ms-excel/email

### ISSUE THREAD

**Issue by rajatbagga** [imdone/imdone#21]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually email stats/updates on the tasks which i am working/or in my backlog for projects that I am working on. I am spending about 30 mins every week to provide the status on the activities which am currently doing and the activities which i am yet to start( ready for action but not started yet). And every month-end I have to provide an update on all the activities which i have completed/Done.

**Describe the solution you'd like**
Since IMDONE  is an offline application, I think it's a good idea to have an option to email the stat's straight out of this application (like status/update on the tasks in Backlog or For Action or Doing or Done column) depending on the column selection (one or multiple column selection). Or maybe if there is an ability to generate a similar report/stats in Ms-Excel from IMDONE which can be shared as  an attachment via email.

For example: 

**DOING** 
| Sno | Project | Task | Start      | Estimate | Spent | Comments   |
|-----|---------|------|------------|----------|-------|------------|
| 1   | xxxxxxx | XYX  | DD/MM/YYYY | 2w       | 1w    | abcdefg... |
|     |         |      |            |          |       |            |
|     |         |      |            |          |       |            |

**Describe alternatives you've considered**
At the moment just manually copying all the tasks which I am working on in an excel sheet template (as per my example above) and filling in the details manually. Most of the information which i am using in the template are already present in IMDONE application which i am using to track my workflow so I believe there should be a way to generate something similar straight from the tool itself. 

**Additional context**
Please refer to the example mentioned above.

**Comment by taubmann** [comment]
From a technical perspective I think it would be easier to use Markdown as export format using a structure like this:
> h1 board name
> h2 slot name
> h3 card title
> card content
> ...
The export should also respect applied filters (e.g. should export only actual visible cards) so you can customize your report.

**Comment by piascikj** [comment]
@rajatbagga If you're familiar with javascript, I just added [Board Actions](https://imdone.io/docs/#/settings?id=board-actions-settingsactions) in imdone 1.6.23.

@taubman Board actions respect applied filters.

The example in the docs should help you get started.

**Comment by rajatbagga** [comment]
Hello Jesse,

Hope you are doing well, I tried to code something as below to download a
csv file instead of putting the data inside the body of the email. But I
was not really successful. Can you please have a look and correct my code
below?  Thank you , Regards Rajat

- name: Download csv for me
function: !<tag:yaml.org,2002:js/function> |-
function anonymous(
) {
let csvContent = 'List,Task,Due,Completed'
csvContent = "data:text/csv;charset=utf-8," + '\n' + csvContent + '\n' +
this.cards.map(task => [task.list, task.text,
task.meta.due, task.meta.completed].join(',')).join('\n')
var encodedUri = encodeURI(csvContent)
var link = document.createElement("a")
link.setAttribute("href", encodedUri)
link.setAttribute("download", "my_data.csv")
document.body.appendChild(link)
link.click();
}

**Comment by rajatbagga** [comment]
Hello Jesse,

I think I know where the issue is. it's when I use # to create markdown
heading in the data (i.e. in task.text) the logic fails. Is there any way
we can fix this issue?

Regards,
Rajat

**Comment by piascikj** [comment]
If you put the # in front of the task does it work?

```
# [my task](#DOING:0)
```

or

```
# #DOING:0 My task
```

**Comment by rajatbagga** [comment]
Putting # in front of a task doesn't work. If i try to keep # in front of a
list name like #Doing i get an error as per the screenshot attached.

Regards,
Rajat

**Comment by piascikj** [comment]
You could remove the `#` in task.text with `task.text.replace(/#/g, '')`

**Comment by rajatbagga** [comment]
Thanks a lot Jesse, this fixes my problem. :)

Regards, Rajat

**Comment by piascikj** [comment]
@rajatbagga Can this issue be closed?

**Comment by rajatbagga** [comment]
Sure, it can be close now. Thanks again. Regards Rajat
