### ISSUE TITLE
Empty daily journal files created in "New File" mode

### ISSUE THREAD

**Issue by trevormeier** [imdone/imdone#23]
imdone is creating empty daily journal files yyyy-mm-dd.md in folders named yyyy-mm in the journal folder with Journal type set to "New file". It appears to happen when the clock rolls over midnight with imdone open, or when imdone is launched.

Board settings:
- Journal type: New File
- Journal folder: /
- New card syntax: MARKDOWN

Version: 1.4.18

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
New File journal type will now only create a single journal file called journal.md
