### ISSUE TITLE
Show custom Metadata as clickable Labels

### ISSUE THREAD

**Issue by taubmann** [imdone/imdone#25]
**Is your feature request related to a problem? Please describe.**

It would be usefull to display custom Metadata as clickable Labels like Tags and Context elements. For example, if you work as a group it would be great to show staff members associated to this task.

**Describe the solution you'd like**

It should be possible to define custom Metadata Keys in Board Settings together with a Color. If a Metadata Item matching a previously defined Key is set in a Card via key:value or via Yaml-Frontmatter, a clickable Label with the Value is shown for each Value (if a key contains a list of values it should populate a Label for each value). Clicking on this label should set the Filter to show only Cards with this Metadata

**Describe alternatives you've considered**

Of course it is possible to show Values via {{meta:key}} but this dosen't behave like Tags and Context Labels.

**Comment by piascikj** [comment]
Mostly implemented, except for the ability to configure which metadata is displayed.  Currently all metadata is displayed.
Would it make more sense to add a setting for metadata keys to exclude from the display?

**Comment by taubmann** [comment]
I would plead for including metadata keys (ideally with a color per key) so the different types of tags are easily spotted

**Comment by piascikj** [comment]
This can now be accomplished with `imdone/style.css`.
