### ISSUE TITLE
1.5.4 minor bugs

### ISSUE THREAD

**Issue by trevormeier** [imdone/imdone#26]
I've had a chance to try out IMDONE 1.5.4 from a fresh install. Here's a laundry list of minor bugs I encountered:
- [x] JS error in first setup creating new project from single file journal template ![Screen Shot 2020-06-10 at 9 46 01 AM](https://user-images.githubusercontent.com/4143559/84304248-14328080-ab0d-11ea-8694-d5217e01caf5.png)
- [x] Creating a new folder in the "new project" dialog moves IMDONE window to front and save dialog behind it. No way to access the save dialog
- [x] Editing file template in board settings or config.yml has no effect
- [x] After ignoring a list, spacebar creates new cards in that list even if I click on a different list
- [x] Unexpected behaviour: no way to select a list so that spacebar creates a new todo in that list. Is based on currently selected card, which isn't intuitive. If no card is selected, spacebar doesn't create a new card anywhere. Should probably default to TODO (or be a setting)

And a few minor annoyances... not quite bugs:
- HTML comments for properties like due and created dates are inconsistent. Created date is in HTML comments; auto-generated due date is not. Could be a board setting?
- [x] Formatting in the editor doesn't indent bullet list items
- [ ] The line-length setting looks for carriage returns, and not total line length after wrapping. So long cards (like the one used to create this list) end up taking up a lot of space in the interface with no way to minimize them. The setting might be better based on word-wrapped line length
- [x] Natural language due-date takes quite a bit to figure out. The syntax requires no colon after "due" and a period at the end of the line. It'd be easier to approach if the syntax was more flexible. The current requirements should be clarified in the documentation
- [x] daily journal markdown files have a bunch of template information from the file template inserted at the top of the file, but without actually calculating the fields. It looks like a copy of the file template? This may be related to the above bug where editing the file template in board settings has no effect. [imdone daily journal example.md.zip](https://github.com/imdone/imdone/files/4760476/imdone.daily.journal.example.md.zip)

**Comment by piascikj** [comment]
@trevormeier I just noticed this issue and am now starting to unpack it.  I know the JS error has been fixed, but I'll be working to reproduce the rest this weekend.

**Comment by piascikj** [comment]
@trevormeier I'll break this out into multiple feature requests.
