### ISSUE TITLE
Drag cards from filtered lists onto another list

### ISSUE THREAD

**Issue by trevormeier** [imdone/imdone#28]
Something I end up doing all the time with unintended effects is dragging cards from a filtered list into another list. It would be useful if IMDONE understood this and moved cards from whatever list they are on to the target list, even though a filtered list is technically just a search result. This would be more in line with how smart searches work in Finder and other macOS apps.

**Comment by piascikj** [comment]
Coming in 1.7.0

**Comment by piascikj** [comment]
Implemented in 1.7.0
