### ISSUE TITLE
Faster card editing workflow

### ISSUE THREAD

**Issue by kaizau** [imdone/imdone#29]
**Is your feature request related to a problem? Please describe.**

More UX nitpick. I'm finding the process to edit cards a bit clunkier than I'm used to coming from Trello. It's a bit of friction that happens dozens of times a day, and streamlining it would make IMDone more enjoyable to use.

Editing a card requires clicking a small icon. Saving an edit requires clicking a button. On a large screen, this means a lot of tracking back and forth.

**Describe the solution you'd like**

- [x] Double clicking a card would open the editor.
- Clicking outside of the editor textarea would either:
  - Automatically save the changes
  - [ ] Show a "save and close" option in addition to "continue editing" and "close editor"
- Pressing "Cmd/Meta + Return" would save and close the editor

**Describe alternatives you've considered**

The keyboard shortcut for editing a card is a plausible alternative, but still requires focusing on the correct card. I find this much more natural with the mouse / trackpad, so doubleclick is strongly preferred to click → keyboard shortcut.

**Comment by piascikj** [comment]
@kaizau There are already [keyboard shortcuts](https://imdone.io/docs/#/settings?id=keyboard-shortcuts) for editing and saving cards.

**Comment by piascikj** [comment]
Double click to edit will be in 1.7.0

**Comment by kaizau** [comment]
@piascikj Awesome, thank you!

Any thoughts on the suggested card-saving flow?

1. `Cmd + Return` to save
2. Blur to save
3. Blur to prompt save + close, continue editing, discard changes

Any one of those would be a big improvement IMO, but (1) could also be combined with either of the blur approaches.

**Comment by piascikj** [comment]
You can do cmd + s to save now.  Doesn't this solve your issue?

**Comment by kaizau** [comment]
Ah, didn't notice that one. Thanks — that solves it. 🙏
