### ISSUE TITLE
Time in format `hh:mm` is not displayed in the card

### ISSUE THREAD

**Issue by cptnnm** [imdone/imdone#33]
**Describe the bug**
Some of my notes contain a time of the day in the format `hh:mm`, e.g. `08:30` (which is a [DIN 8601](https://en.wikipedia.org/wiki/ISO_8601#Ordinal_dates) format).
The date is not being displayed in the board view. 

**To Reproduce**
1. Create a card and add a text representing a time of the day in the format `hh:mm`, e.g. `08:30`
2. Save the card to go back to the board
3. See error

**Expected behavior**
The time is being displayed.

**Screenshots**
<img src="https://user-images.githubusercontent.com/3016212/95665780-c5950180-0b53-11eb-9f2d-2c24594037c3.png" width="500"/>
<img src="https://user-images.githubusercontent.com/3016212/95665779-c332a780-0b53-11eb-9129-685ae2baf414.png" width="500"/>

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS 64-bit
 - imdone 1.5.9

**DoD**
- [x] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by piascikj** [comment]
This is fixed in imdone 1.5.11.  Thanks for reporting!
