### ISSUE TITLE
Keep metadata together

### ISSUE THREAD

**Issue by telenieko** [imdone/imdone#36]
Hi,

Currently, if you have a card like that (in an md file):

```
<!-- #TODO:0 Complete a task
due:2020-12-05
 -->
```

When you move it to done, it will end up like:

```
<!-- #DONE:15 Complete a task <!-- completed:2020-12-05T15:47:51.372Z -->
due:2020-12-05
 -->
```

There are two issues with that:

  - Ugliness when reading.
  - I think HTML does not allow for nested comments

At least on cards which already have a metadata line (in this case the `due` one) imdone should add the completed metadata to that line. Which would result in:

```
<!-- #DONE:15 Complete a task
due:2020-12-05 completed:2020-12-05T15:47:51.372Z
 -->
```

IMHO, it reads better. And metadata stays together

**Comment by piascikj** [comment]
@telenieko I fixed this in 1.6.10 and it's currently available for download.

Thanks for reporting and let me know what you think.
