### ISSUE TITLE
Show a "save and close" option in addition to "continue editing" and "close editor"

### ISSUE THREAD

**Issue by piascikj** [imdone/imdone#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jtmusky** [comment]
Would there be a way to bypass the save dialog? Possibly if using the a vim style editing mode. i.e. `ZZ` or `:wq` related: #48

**Comment by piascikj** [comment]
Use cmd or ctrl + s

**Comment by piascikj** [comment]
implemented in 1.11.0
