### ISSUE TITLE
Internal vim editing mode

### ISSUE THREAD

**Issue by jtmusky** [imdone/imdone#48]
Please support vim editing mode within the internal editor.

**Comment by piascikj** [comment]
It's coming!
![Screen Shot 2021-02-18 at 8 57 07 AM](https://user-images.githubusercontent.com/233505/108367979-2fcf4a00-71b7-11eb-8bf2-4b3bb9507761.png)

**Comment by piascikj** [comment]
I'm adding `:q`, `:q!`, `:wq` and `:x` as well

**Comment by piascikj** [comment]
implemented in 1.11.0
