### ISSUE TITLE
Without closing main app: Project fails to reopen after closing. (Portable Windows)

### ISSUE THREAD

**Issue by jtmusky** [imdone/imdone#52]
**Describe the bug**
With the main app open, project fail to reopen after closing. The project opening dialog only indicates a spinning icon. If you close the project that is currently spinning, it displays the following error.

**To Reproduce**
1. Open a project
2. Close the project without closing the main application, Clicking the small "x" on the right side corner of the project tab.
3. Click on the "Add a project"
4. Choose from the "Recent projects" list the previous project closed mentioned above

**Expected behavior**
Project loads

**Screenshots**
![2021-02-22 13_16_44-imdone 1 11 0 - C__Users_JMusgrove_code_imdone_testin git](https://user-images.githubusercontent.com/23535616/108758187-6affaf00-7510-11eb-9dd8-3798cbad545c.png)
![2021-02-22 13_16_54-Error](https://user-images.githubusercontent.com/23535616/108758198-6f2bcc80-7510-11eb-8c26-495889abebd0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.11.0 *(Portable)*

**Additional context**

**DoD**
- [ ] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by jtmusky** [comment]
This bug happens in the "Installer" Version for windows 10.

**Comment by piascikj** [comment]
@jtmusky Can you try to reproduce this issue and post the **imdone log file**?

**Comment by jtmusky** [comment]
> @jtmusky Can you try to reproduce this issue and post the **imdone log file**?

Yep 👍, I'll get this done when I get to work tomorrow.

**Comment by jtmusky** [comment]
Fixed in release 1.12.0
