### ISSUE TITLE
Allow for Completion Date interact with Due Date

### ISSUE THREAD

**Issue by rismay** [imdone/imdone#6]
**Is your feature request related to a problem? Please describe.**
Currently there is a fleshed out concept of "due date" in the app. It would be nice to see "completion date" get the same treatment.

**Describe the solution you'd like**
The functionality could be as simple as removing the "due date" badge and switching it to a "completed xx-xx-xx" and changing the color green if it was completed before or on the due date. red if it was completed late.

**Comment by piascikj** [comment]
I think this is a great idea and something I've been planning on adding to 1.5.0.  It looks like this would require the user to at least configure the name of the list that would trigger the completed date to be added to a card.
