### ISSUE TITLE
equivalent methods of data entry in yml headers do not work

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#67]
**Is your feature request related to a problem? Please describe.**

specifying tags in the yml header in the below format does **not** work:

```yml
---
tags: tag1, tag2
---
```
**Describe the solution you'd like**
equivalent yml formats should be supported

**Describe alternatives you've considered**
specifying tags in this format does work:
```yml
---
tags:
 - tag1
 - tag2
---
```
but the earlier format is more concise, so I prefer that

**Additional context**
the same issue applies to config.yml

**Comment by piascikj** [comment]
The YAML spec says collections can be on a single line when surrounded by square brackets. https://yaml.org/spec/1.2/spec.html#id2759963
