### ISSUE TITLE
Imdone could be more space efficient.

### ISSUE THREAD

**Issue by johnblommers** [imdone/imdone#71]
**Is your feature request related to a problem? Please describe.**
It's hard to get Imdone to display a lot of cards and columns without zooming out to the point the  board becomes unreadable except on the largest monitor.

**Describe the solution you'd like**
There seems to be a fair mount of dead space in the Imdone board. Can that be made more compact? Now let me add that Imdone is a pleasant enough to view and use, but it takes a lot more panning and scrolling to move about among  the cards.
**Describe alternatives you've considered**
Take a look at [this Trello board](https://trello.com/b/mxaCZTVc/ubuntu-desktop-common)  and notice how many cards fit in  the window. That's what I'm talking about.

**Comment by JJSlote** [comment]
Try placing the following on any card, far enough from the top that it'll be in effect only when the card is expanded. It's a style spec that will apply to all your open cards and tabs.

`<style>
.card.list {
    width: 8.71vw !important;
min-width: 8.71vw !important;}
</style>`

Rgds - Jerome

**Comment by manogna4** [comment]
> Try placing the following on any card, far enough from the top that it'll be in effect only when the card is expanded. It's a style spec that will apply to all your open cards and tabs.
> 
> `<style> .card.list { width: 8.71vw !important; min-width: 8.71vw !important;} </style>`
> 
> Rgds - Jerome

wow, nice.
I don't recollect seeing this in the documentation. Did I miss a section?

Is there a way to do this from config.yml?

**Comment by JJSlote** [comment]
Nope, it's not in the documentation. I think Jesse has a formal CSS capability in the works. We can use View > Toggle Developer Tools to look at the document object model and discover what every element is called, but it takes some CSS expertise.
Rgds - Jerome

**Comment by johnblommers** [comment]
Fantastic! I am **so** glad I asked :-)

**Comment by manogna4** [comment]
> Nope, it's not in the documentation. I think Jesse has a formal CSS capability in the works. We can use View > Toggle Developer Tools to look at the document object model and discover what every element is called, but it takes some CSS expertise.
> Rgds - Jerome

This is enough to get me started making some minor modifications to the look. Am I right in assuming that any style specifications in a card gets applied to the whole board?

What happens if 2 cards have different style specs?

**Comment by JJSlote** [comment]
> Am I right in assuming that any style specifications in a card gets applied to the whole board?
> What happens if 2 cards have different style specs?

1. They hit all your open tabs, not just the board they're in. 2. Conflicting style specs? Last one, based on its position in the document, should prevail. 

If you're going to be working with imdone a lot, it's extremely satisfying to make it your own via style touch-ups. Enjoy the discovering!! 

Rgds - Jerome

**Comment by piascikj** [comment]
@johnblommers This can be accomplished through a custom css for your project.
[Advanced Topics - Custom css](https://imdone.io/docs/#/advanced-topics?id=custom-css-beta-feature)
