### ISSUE TITLE
Replace the ctrl+shift keybinding to show all cards

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#72]
**Is your feature request related to a problem? Please describe.**
The `show all cards` functionality gets triggered when I try to use other `ctrl+shift+...` keybindings (dev tools, for example).

It also makes the keybinding more cumbersome for those using sticky-keys for the modifiers (but this won't affect many users)

**Describe the solution you'd like**
have a different keybinding. for eg, `A` to toggle the `all` mode on and off..

**Describe alternatives you've considered**
--not applicable--

**Comment by jtmusky** [comment]
I like the way this is working, I think it needs a little more tweaking. Can we make this a toggle vs holding down shift. Plus, would be nice shrink all the columns down so I can see all of them. Currently I need I have  to manually zoom out `ctrl -` then show all filter/columns. Plus, I moving the cards around is a little tricky.

-JM
