### ISSUE TITLE
improving markdown compatibility of the `MARKDOWN` card format

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#74]
**Is your feature request related to a problem? Please describe.**
The benefit of this format since it allows me to just tag the beginning of any line in a markdown file in any app and then manage it in imdone. While task entry is possible (and easy) in imdone, writing in a markdown file is still the best way to brain-dump a large number of ideas.

A limitation with this approch is that imdone only recognizes tags in the form `#todo:<number>` (notice the colon) (`<number>` is optional).

The problem here is that just tagging `#todo` is not enough for imdone to recognize it, and I have add the colon. So a markdown journal could be filled with lines that have `#todo` tags in the beginning, but only those with the `:` get picked up. This seems counter-intuitive.

**Describe the solution you'd like**
Encode the card order else where in the markdown entry, like described in [this issue](https://github.com/imdone/imdone/issues/73). This eliminates the need for `:<number>`

**Describe alternatives you've considered**
The `MARKDOWN` format is an alternate, but needs a lot more syntax, and isn't as intuitive.

**Comment by piascikj** [comment]
Implemented in imdone 1.30.2
