### ISSUE TITLE
make the number of blank lines that terminates a card configurable

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#75]
**Is your feature request related to a problem? Please describe.**
imdone uses a blank line to terminate cards in a markdown journal.

markdown specs recommend (but not insist on) having a single blank line after many elements such as headings, code blocks. many markdown linters flag such instances.

So, a journal file written with a recommended markdown format would not be properly recognized by imdone.

While I see the visual appeal (in a markdown journal) in having a blank line terminate a card, there is a functional price to pay for those used to writing in markdown.

for example, not allowing blank lines (except to terminate cards) means that certain markdown grammar such as:

```html
<!--blank line-->
---
<!--blank line-->
```
to show horizontal rules cannot be used. This is because if there is no blank line before `---` the previous line becomes a header (H1)

**Describe the solution you'd like**
I'd like to suggest using 2 blank lines instead of 1 as a markdown separator. I am not aware of a markdown spec that recommends 2 blank lines. It retains most of the visual appeal while agreeing with the recommended markdown spec.

I understand this is a breaking change for some. I guess the number of lines to act as a card terminator could be encoded in the `config.yml` file with the default option being `1` to cater to existing users.

Making the number of lines configurable (as opposed to just using 2) allows a user to have their own formats (3 blank lines, for instance) while not breaking basic markdown.

**Comment by piascikj** [comment]
Cards now terminate with 2 blank lines
