### ISSUE TITLE
increase size of filter box

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#76]
**Is your feature request related to a problem? Please describe.**
Filters may be long enough to exceed the space provided by the filter box. 

**Describe the solution you'd like**
There is a lot of unused space next to the filter box. It could be used to increase the size of the box

![image](https://user-images.githubusercontent.com/16304061/111241659-97947b80-8623-11eb-9892-ff0c5dc2057b.png)

**Comment by JJSlote** [comment]
We can control this via the style card. Try:

` div.field.filter-field > div.autocomplete{width: 55em !important;}`

Electron apps flex like web sites. Users with different screen sizes, or who aren't using imdone full-screen, won't show the same vacant space.

Rgds - Jerome

**Comment by jtmusky** [comment]
Can we make the filter field hidden all together and only show when needed? e.g. `ctrt/cmd + f` And possibly hide the "add a card", I don't think I have ever clicked that button.

**Comment by JJSlote** [comment]
> 
> 
> Can we make the filter field hidden all together and only show when needed? e.g. `ctrt/cmd + f` And possibly hide the "add a card", I don't think I have ever clicked that button.

1. Not with CSS alone
2. Sure, I've done the same. Try:
`div.card-footer{display:none !important;}`

Rgds - Jerome

**Comment by manogna4** [comment]
> Electron apps flex like web sites. Users with different screen sizes, or who aren't using imdone full-screen, won't show the same vacant space.

I understand you. But, the screenshot I shared had the app window width around 1200px, which I believe is less than what most people use on a desktop. IMO, that's wasted space.

It's probably just me, but I wouldn't mind having the filter box span the entire empty width (like an address bar in a browser).
