### ISSUE TITLE
AUR installation for Arch Linux Distros

### ISSUE THREAD

**Issue by santiyounger** [imdone/imdone#77]
It'd be great to be able to install Imdone from the AUR ( Arch User Repository). This can help of course all users of Arch Linux, as well as arch based distros like manjaro and Garuda for example.

---

It's currently tricky to install Imdone in Arch Linux, even though there will be Appimage installation options soon, AUR is the best way to quickly update Imdone on new releases.

## Current work around
The best way I've managed to install Imdone on my Linux machine is through a tool called "debtap" which is a bit of a cumbersome process to install .deb in arch based distros.

Imdone still works great with this method, but updating it means repeating the installation process from scratch which can become an annoyance.

This is why it'd be amazing to add Imdone  to the AUR

Thanks a lot, and keep up the excellent work!

**Comment by xee5ch** [comment]
@piascikj I have a working AUR PKGBUILD that will use the same approach those use for, free or non-free, to download a Debian-based .deb package and install it like you would do for Chrome. Obviously similar software and similar deployment method, and low effort for community people like me to work on with you.

https://gist.github.com/xee5ch/33134997efbf6f399ac6909c2ce51489

I just used to upgrade this on my personal machine. I have not packaged it for the AUR volunteer repository system. It is non-free, so it will not make it into official repos anyway. But, I wanted to clear things with you before I move forward.

1. Are you ok with me publishing a build script as a community contributor to the [AUR](https://aur.archlinux.org)?
2. Would you prefer to maintain it at first or in the long run? Are you comfortable with me being a maintainer of the script, and potentially others I do not know if I later orphan it?
3. If I become busy and orphan it and you are ok with me taking care of it re 1 and 2, would you prefer I give you notice prior to oprhaning it?
4. If you want, we can talk out of band, if you use CI/CD to automate releases, do you want you or I automatically updating the AUR build script (it is done through git but there is a user review process) so one of us does not have to manually review updates and edit the build script? Effort is minimal, but not sure how you do this yourself? :-)

**Comment by santiyounger** [comment]
This is very exciting thanks for all the work on this @xee5ch This would be extremly useful, For arch linux distro's the updating process is usually really cumbersome, so this would make updating really fast! 

Excited to see what Jesse @piascikj thinks about your questions, I'll for sure keep an eye on this, thanks!

**Comment by xee5ch** [comment]
I haven't heard back, but I needed it, so ... I did it. (Sorry, Jesse.)

I just updated to 1.19.3 so I did not have to update by hand.

https://aur.archlinux.org/packages/imdone-bin/

**Comment by santiyounger** [comment]
@xee5ch thanks for doing that, appreciate it tons!

**Comment by piascikj** [comment]
@xee5ch Sorry, I thought I had responded with a "go ahead" weeks ago.  Must have forgotten to hit send.

It would be great to have it automated.  Let's chat.

**Comment by piascikj** [comment]
This appears to be done
