### ISSUE TITLE
"Open file" link on card no longer opens file in Obsidian

### ISSUE THREAD

**Issue by brookscl** [imdone/imdone#79]
**Describe the bug**
When I click the "Open file" link, Obsidian opens at the currently opened file (i.e., it just activates Obsidian) and not the file containing the card.

**To Reproduce**
1. Click the "Open card" button on the top of a card
2. See that Obsidian opens but doesn't not switch to file containing the card

**Expected behavior**
Should go directly to the card. In fact, this worked previously and it might be related to me moving my Obsidian vault from a DropBox folder to an iCloud document folder.

**Desktop (please complete the following information):**
 - OS: macOS 11.2.3
 - Imdone Version 1.15.1
 - Obsidian version 0.11.9

**DoD**
- [ ] Issue is understood
- [ ] Fix is implemented and tested
- [ ] Fix is deployed in the current release

**Comment by piascikj** [comment]
Can you try upgrading to imdone 1.5.3?

**Comment by brookscl** [comment]
I'm on 1.15.3 right now and same behavior.

**Comment by piascikj** [comment]
Can you try removing the plugin directory `.obsidian/plugins/imdone-obsidian-plugin` and then adding the plugin again?

**Comment by brookscl** [comment]
That worked!
