### ISSUE TITLE
Allow 'taskPrefix' in settings to be interpolated.

### ISSUE THREAD

**Issue by bduplanty** [imdone/imdone#82]
**Is your feature request related to a problem? Please describe.**
In using jrnl.sh as my journal entry tool of choice and pointing imdone to the journal file, adding a card in imdone does not fit the jrnl.sh format.  With a tweak to a piece of functionality, imdone could easily be configured to add cards with the format more usable by jrnl as well.

**Describe the solution you'd like**
- All the taskPrefix setting to interpolate   taskPrefix: '[${(new Date()).toISOString()}]' 
- Jrnl.sh entries need to look like [2021-03-31 13:14] #TODO:0 Testing - Prepend card column designation

**Describe alternatives you've considered**
Currently adding tasks/cards via jrnl to get the date/time stamp, and then go into imdone for further editing when needed.  Just looking for more efficient method.

**Additional context**
Be able to set in Board Settings - 
![Screen Shot 2021-03-31 at 4 13 24 PM](https://user-images.githubusercontent.com/33303709/113222670-5794e180-923c-11eb-8c15-9dbf662833f8.png)

**Comment by piascikj** [comment]
Implemented in 1.16.4
