### ISSUE TITLE
some legal yaml formats not supported

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#89]
**Describe the bug**
some legal yaml formats are not supported. 

**To Reproduce**

The following does not work:

```yaml
---
tags: tag1, tag2
---
```

The following works:
```yaml
---
tags:
 - tag1
 - tag2
---
```

**Expected behavior**
according to yaml specifications the above 2 cases are equivalent and imdone should support them both

**Screenshots**
-- not needed --

**Desktop (please complete the following information):**
windows 10
imdone 1.16.3 (but seen in previous versions too)

**Additional context**
I see the same issue with `config.yml` too
So, it's probably there in other places that use yml.

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
The YAML spec says collections can be on a single line when surrounded by square brackets. https://yaml.org/spec/1.2/spec.html#id2759963
