### ISSUE TITLE
unable to set *no* task prefix

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#90]
**Describe the bug**
cannot configure settings to not have a task prefix

**To Reproduce**

The `save settings` button becomes inactive if `prefix for new cards:` is left blank

`taskPrefix: ''` in `config.yml` seems to insert a space before a task

**Expected behavior**
1. ui should allow a blank for `prefix for new cards:`
2. `taskPrefix: ''` should work

**Screenshots**
-- not applicable --

**Desktop (please complete the following information):**
 - OS: windows 10
 - Imdone Version 1.16.3

**Additional context**
discussed on discord
https://discord.com/channels/795464756541521931/795464756541521934/829369972739276810

**DoD**
- [x] Issue is understood
- [x] Fix is implemented and tested
- [x] Fix is deployed in the current release

**Comment by piascikj** [comment]
Fixed in imdone 1.16.4
