### ISSUE TITLE
allow choice of `#` and/or `+` tags format

### ISSUE THREAD

**Issue by manogna4** [imdone/imdone#92]
**Is your feature request related to a problem? Please describe.**
I use `+` a lot in my task descriptions for non tag related reasons. imdone recognizes something like `+something` as a `something` tag. I understand that the `+` tag comes from todo.txt roots...

**Describe the solution you'd like**
Have a configuration option to choose tag formats.
It might even be beneficial to allow other character prefixes.

**Describe alternatives you've considered**
there seems to be no way to avoid +text to be recognized as a tag without redoing lots of markdown notes

**Comment by piascikj** [comment]
Implemented in 1.22.1
