### ISSUE TITLE
Maintain expanded view of card after clicking task

### ISSUE THREAD

**Issue by timjore** [imdone/imdone#99]
**Is your feature request related to a problem? Please describe.**
When I expand any card on the board to view more details, the cards remain expanded until I click a checkmark on any card to toggle a task, then every card that is expanded automatically collapses.

**Describe the solution you'd like**
I would like expanded cards to remain expanded after a task has been clicked and only collapse when the collapse button is clicked.

**Describe alternatives you've considered**
_No known alternatives._

**Comment by msander1983** [comment]
I second this request! :) 

Here's what the problem looks like: 

![imdone bug 20210427201944](https://user-images.githubusercontent.com/17176751/116292677-41743580-a796-11eb-9d50-c012658ad863.gif)

**Comment by piascikj** [comment]
In 1.18.3
